### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by piesieomane** [rotshidzw/Catalog-of-my-things#28]
In this Pull Request the following list below was implemented;

- We are a group of three people consisting of @piesieomane  , @rotshidzw  and @Abdullah2213565 

- Task distribution is as follows

Member 1: @Abdullah2213565 
Member 2: @rotshidzw 
Member 3: @piesieomane 
Workload distribution can be found here
https://github.com/rotshidzw/Catalog-of-my-things/projects/1

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @rotshidzw, @piesieomane, and @Abdullah2213565👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
- [ ] Some of the task cards don't have descriptions, Please make sure to add descriptions to all of your task cards.
![image](https://user-images.githubusercontent.com/83803414/194877375-3c137b9d-8b47-43b3-8c9e-830df426bee8.png)

- [ ] Time estimate distributions should be fair (no single person should be doing all of the most time-consuming tasks). The points are not divided equally among team members. Please make sure the point distributions are fair and equal.
- [ ] #8 Please also add points to this task card.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] As requested by the previous reviewer kindly ensure all tasks have descriptions. Kindly add a description for this task

  ![ddj](https://user-images.githubusercontent.com/81468675/194898008-4607cea8-91d7-4348-8a0c-e12578fb3f24.jpg)

- [ ] Kindly add number of points to this task

  ![fkli](https://user-images.githubusercontent.com/81468675/194898100-f54c58a1-451e-4cbc-a7fd-4db3b785ed44.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CollinsTatang** [comment]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
